apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
# Pinned by digest by the build pipeline.
images:
- digest: sha256:bc2db6908cc6641b5ef80fdbd0486012f92477a97ad2c00aa2359c731679f8dd
  name: mlflow
  newName: europe-west2-docker.pkg.dev/hl-llm-p2p-261007/llm-p2p/mlflow
