apiVersion: v1
kind: Service
metadata:
  name: model-server-v1
  labels:
    app.kubernetes.io/name: model-server
    model-version: v1
spec:
  selector:
    app.kubernetes.io/name: model-server
    model-version: v1
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: model-server
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
